### ISSUE TITLE
Credit to whom it is due?

### ISSUE THREAD

**Issue by mbello** [miguelgrinberg/aio-executor#1]
If you took inspiration from https://gist.github.com/vxgmichel/d16e66d1107a369877f6ef7e646ac2e5
you should give Vincent Michel his deserved credit.

This is a nice addition to that work, though.

**Comment by miguelgrinberg** [comment]
I haven't seen that version, actually. The idea is not really that original, I wrote my version and only then started seeing other implementations. I have found these two:

https://gist.github.com/seglberg/0b4487b57b4fd425c56ad72aba9971be
https://github.com/Python-Tools/asyncio-executor

Why would you assume I would be okay copying someone else's code and pass it as mine?

**Comment by miguelgrinberg** [comment]
I have updated the README with links to all these other versions.
